---
apiVersion: v1
kind: Service
metadata:
    name: redis-service
    namespace: ipgeolocation
spec:
  type: ClusterIP
  selector:
      app: redis
      name: Redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379