---
apiVersion: v1
kind: Service
metadata:
  name: ip-geolocation-frontend-service
  namespace: ipgeolocation
spec:
  type: ClusterIP
  selector:
    app: ip-geolocation-frontend
    name: Frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
#     nodePort: 30081