---
apiVersion: v1
kind: pod
metadata:
  name: nginx
  namespace: ipgeolocation
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
  nodeSelector:
    disk=nvme